New - Ajout du système de plages de non-dispo
sheaft-app/portal pull request #5
Opened 2021-04-07 17:11 UTC by geoffreymugnier

2021-04-08 06:51 UTC, noelmugnier requested changes

2021-04-08 06:51 UTC, noelmugnier commented on src/routes/selling-points/ManageYearlyClosingsModal.svelte
> +              "Une erreur est survenue pendant la demande de création du bon de préparation."
Le petit copier coller qui traine ;)

2021-04-10 12:42 UTC, geoffreymugnier commented on src/routes/selling-points/ManageYearlyClosingsModal.svelte
> +              "Une erreur est survenue pendant la demande de création du bon de préparation."
Oupe

2021-04-10 15:01 UTC, noelmugnier approved these changes

2021-04-10 15:01 UTC, merged